### PR TITLE
Consolidated table and 3 person comparison

### PR DESCRIPTION
**Pull request by ellackane**
I think that my pull request from yesterday went wrong. I'm trying it again although there might not be new information. This should contain "Consolidated PEW Table" and "3 person feat comparison"

### CODE REVIEW

**Comment by djperrefort** [comment]
Or, if you prefer, I can help clean up the repository instead. Your choice.

**Comment by ellackane** [comment]
Sorry about that, I am honestly still confused about submitting pull requests. How can I change a PR? Or should I just delete duplicate files from the repository?

**Comment by djperrefort** [comment]
No worries! The PR will automatically update to reflect any changes you make in the branch you are trying to merge. Just edit the branch and then commit / push your changes.

**Comment by ellackane** [comment]
Ok will do. Where do you recommend I keep like intermediate code that I don't want to delete but also isn't the final product I want to merge?

**Comment by djperrefort** [comment]
I would argue that such code shouldn't exist. Any code that is relevant to the project should be included in the repository.

**Comment by ellackane** [comment]
Ok that makes sense. I think that I fixed all of the issues with my branch. Will you please check to make sure that everything is fine?

**Comment by djperrefort** [comment]
Go ahead and merge this in. I'll follow up with another PR that organizes some of the conflicting information that has been added from previous merges into master.

**Pull request merged**
